POST http://localhost:8080/anonymous-posts/comment/like/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJiMDY3NWM0NS0wNmYyLTQ1YTEtYTViOC1mYWNjNDg1ZmI5OWIiLCJleHAiOjE3MDgxMjQ4ODQsImF1dGhvcml0aWVzIjpbIlNUVURFTlQiXX0.Rp5r_NKuLRDWNz_27ipvLZULmAiiRpkITyGzT8csfGZ0a_gpQgyIOYzt-o1zdSZ1HngTW3xBMXpndq6s3hTZxw
