GET http://localhost:8080/anonymous-posts/frames?size=60&pageNumber=0
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI0YmJkYWYxYS0yMTc5LTQ2ZDQtYWJmZi1lMTgwNDFmYTA0NzIiLCJleHAiOjE3MTIxNjM1MzYsImF1dGhvcml0aWVzIjpbIlJPTEVfU1RVREVOVCJdfQ.1d5VTmjvV3nZyhgNTC2XDgrHm4kesDr8yhoCnIatPhyQP5h5GEF3aNDs5FLRGb6vBHn01s68iSUkNDtE5yTKZw