DELETE http://localhost:8080/anonymous-posts/frames/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjMWVkNWUyZC1iZTE4LTRmODMtYmFkOS0wMDAxNWRlNTlhOGUiLCJleHAiOjE3MDgyMjMyNDYsImF1dGhvcml0aWVzIjpbIlNUVURFTlQiXX0.40Krnz8hc73Tg6X5h5jB3_G_ZcsRhdReOb24DKn-ulqwDCS0IoCbM6VkEErnxgrgH3inRQ7ZuZ7bmDZ-uohaYg