GET http://localhost:8080/anonymous-posts/?size=60&pageNumber=0
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlZDE4N2Q2MC01Njk3LTRkODgtYTVjMy1kZGYwYmY2ODdlMGEiLCJleHAiOjE3MDgxMjU4NTEsImF1dGhvcml0aWVzIjpbIlNUVURFTlQiXX0.cWFzjP62zbvsrCFoLzEiM8i6GWwb1h69uLR3RK2zmEkhPbFf4oI1DO8yYAd9kYOgKE2K-FODvEBSDWKzasWQLQ