POST http://localhost:8080/anonymous-posts/comment/1?content=nicepost1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2YTI3N2YxZi0yMGJhLTQ0YmMtYjExOS1jMDVkOTYxOTFmOTMiLCJleHAiOjE3MDEyNDIwMjUsImF1dGhvcml0aWVzIjpbIlNUVURFTlQiXX0.XO_GkmyR4ZePH_JF0B1eHEw3xFFtLf9Nux4aiA5FDoQNqHhLa3RozqEKxEym1aIyHpjhe5ZpSbYyq7wwNJovbA
