GET http://localhost:8080/anonymous-posts/?size=7&pageNumber=0
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlOTk4MjRhNC03YTk5LTQ4OTktOTg0OS1hYzA5ZjQ5OGNjODAiLCJleHAiOjE3MDc2MjA5ODgsImF1dGhvcml0aWVzIjpbIlNUVURFTlQiXX0.8waEDgqDvEp68LvP1nzgNCen1ky7eZduJlAhHwegDfckJ3SYek44XQ0Gm2db9l-tF2pZ5uPisS2IbrqViIbi5w