GET http://localhost:8080/anonymous-posts/frames/get-current-frame
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2ODY2MTUwYy1jNDA0LTQzNGYtYTg1MS1iZWY3NTE0ZTM1NDMiLCJleHAiOjE3MDA3Mjc0MDAsImF1dGhvcml0aWVzIjpbIlNUVURFTlQiXX0.rAPwhXlOt9u6lZLErN-0SJkSa8wMIhrfHcL0eUXb5Hzwl8TF9gt47x8eiD1yxb7RzklkcxC59glaQfy-n0pz0w
