PATCH http://localhost:8080/anonymous-posts/comment/1?content=Nice+Postpostpost
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2YTI3N2YxZi0yMGJhLTQ0YmMtYjExOS1jMDVkOTYxOTFmOTMiLCJleHAiOjE3MDEyNDI3MjcsImF1dGhvcml0aWVzIjpbIlNUVURFTlQiXX0.LRR8XhWRV-WPXkH8eLV07iWwdd6qGM7KV3Rsv_O25y28YlYXe7cUpbvM_kRI0Ze7IsIjRny5CL1kfakLNMwueg