DELETE http://localhost:8080/anonymous-posts/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2YTI3N2YxZi0yMGJhLTQ0YmMtYjExOS1jMDVkOTYxOTFmOTMiLCJleHAiOjE3MDEyNDIyOTQsImF1dGhvcml0aWVzIjpbIlNUVURFTlQiXX0.tB83CSJU3NJbNFKU6yyNgvlU4tAkmgp9DqTplxi-Mmgjgq36lVvhHYdsdwp2j24os9z-RjmCLgvy1iEN4OCBUg