DELETE http://localhost:8080/anonymous-posts/like/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2YTI3N2YxZi0yMGJhLTQ0YmMtYjExOS1jMDVkOTYxOTFmOTMiLCJleHAiOjE3MDEyNDI1MDQsImF1dGhvcml0aWVzIjpbIlNUVURFTlQiXX0.1Y1ZAlCZXMZCzfwgfxs6UQD_ZPaJDKhXyRNLgl3dSDuww5dDMDFnT1vJwJwOq8uBJbmkWlCKlZQ0eUMXen8Wiw