POST http://localhost:8080/anonymous-posts/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIwYzhmZWI2OS1mYzA0LTRlNzctYmYyZi1jOGIwNTY4NjIyYTMiLCJleHAiOjE3MDM5MDMxOTYsImF1dGhvcml0aWVzIjpbIlNUVURFTlQiXX0.MuuXj05EtP1mkynUE9DsqsO5gDHNdsxyiNAnqrlciaN2-eNetPU1wJgdd9vzGJDGfVE3rZjr8vr9l1X0gF6sSQContent-Type: application/json

{
  "usernamePublic": true
}