GET http://localhost:8080/anonymous-posts/frames/get-current-frame
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlMWNmNDVhNi0wZTRlLTQ4Y2QtOTAzNi0xMzE5Njc3NTM3OTEiLCJleHAiOjE3MDM5MjUxNTAsImF1dGhvcml0aWVzIjpbIlNUVURFTlQiXX0.-7EuIsxgSW38LwhC-Y5UfOUXLjltwn8CYyYGcIFTX8__MDUvCZjQ3mcsfNMPJD61zMRyLo270NMXioVjXhCIVw