POST http://localhost:8080/anonymous-posts/like/40
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlZDE4N2Q2MC01Njk3LTRkODgtYTVjMy1kZGYwYmY2ODdlMGEiLCJleHAiOjE3MDgxMjU3ODQsImF1dGhvcml0aWVzIjpbIlNUVURFTlQiXX0.SjjRivhf648CLgXeHw7MxnL53DgmQhrbcrtSQJUQMx1UijCmxB1ZZFUfCL5SAr5blhwpqo-QTC6Kv1UyRx019w