GET http://localhost:8080/anonymous-posts/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2MzliNmM3MC02Y2I2LTRlZjgtYjlkOC00NWY4ODAyN2E0ZmEiLCJleHAiOjE3MDI2OTc0OTMsImF1dGhvcml0aWVzIjpbIlNUVURFTlQiXX0.lAgr9cJmmzkx519j8iYxCsuLpmUCm29kuCbz259FahxFd-TIE3T_SEjxiKt1WiMGsGwdCDbG4zm-A8vyh5a_Lw