PATCH http://localhost:8080/users/change-username?username=valodik
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlZDE4N2Q2MC01Njk3LTRkODgtYTVjMy1kZGYwYmY2ODdlMGEiLCJleHAiOjE3MDgxMjU2MzMsImF1dGhvcml0aWVzIjpbIlNUVURFTlQiXX0.j3tAef76GE6fbEKSd8ro7ejmrJ7ZWJIKVZmVoZkNo__ImYJ-gAl7TEvMGXZnibt1wodFnFen8KX46IH0ZK6uOA