PATCH http://localhost:8080/users/change-username?username=valodik
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5ZmFlZDgyYy1jNGYwLTQzZTQtOTE4NC03ZmY4M2UyMDA5ZTMiLCJleHAiOjE3MDEyNTA0MTEsImF1dGhvcml0aWVzIjpbIlNUVURFTlQiXX0.n1Qy9VPIG09Gi4VJjqVdgHodewNq2I3-MJ1uxlGxiiXaqXwyBILsc0PbT7vmmm7MTPUPERYKe8GwFy-TpRJKRw