package com.anonymous.enums;

public enum Major {
        COMPUTER_SCIENCE,
        ELECTRICAL_ENGINEERING,
        MECHANICAL_ENGINEERING,
        CIVIL_ENGINEERING,
        CHEMICAL_ENGINEERING,
        BIOMEDICAL_ENGINEERING,
        AEROSPACE_ENGINEERING,
        INDUSTRIAL_ENGINEERING,
        SOFTWARE_ENGINEERING,
        MATERIALS_ENGINEERING,
        PETROLEUM_ENGINEERING,
        ENVIRONMENTAL_ENGINEERING,
        NUCLEAR_ENGINEERING,
        ARCHITECTURAL_ENGINEERING,
        GEOLOGICAL_ENGINEERING,
        MINING_ENGINEERING,
        OCEAN_ENGINEERING,
        SYSTEMS_ENGINEERING,
        OTHER
}
